<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Executive Business Report - Ogani</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        
        body {
            font-family: 'Inter', sans-serif;
            color: #333;
            margin: 0;
            padding: 40px;
            background: #fff;
            line-height: 1.6;
        }
        
        .header {
            border-bottom: 2px solid #2B5C38;
            padding-bottom: 20px;
            margin-bottom: 30px;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
        }
        
        .brand {
            display: flex;
            align-items: center;
            gap: 15px;
        }
        
        .logo {
            width: 50px;
            height: 50px;
            background: #4BAE4F;
            border-radius: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: bold;
            font-size: 24px;
        }
        
        .title h1 {
            margin: 0;
            font-size: 28px;
            color: #1a1a1a;
            font-weight: 700;
        }
        
        .title p {
            margin: 4px 0 0 0;
            color: #666;
            font-size: 14px;
        }
        
        .meta {
            text-align: right;
            font-size: 14px;
            color: #555;
        }
        
        .meta p {
            margin: 4px 0;
        }
        
        .kpi-container {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 20px;
            margin-bottom: 40px;
        }
        
        .kpi-card {
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 20px;
        }
        
        .kpi-label {
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: #6b7280;
            margin-bottom: 8px;
            font-weight: 600;
        }
        
        .kpi-value {
            font-size: 24px;
            font-weight: 700;
            color: #111827;
            margin: 0;
        }
        
        .section-title {
            font-size: 18px;
            font-weight: 600;
            color: #1f2937;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 10px;
            margin-bottom: 20px;
            margin-top: 40px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
            margin-bottom: 30px;
        }
        
        th, td {
            padding: 12px 16px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        
        th {
            background-color: #f9fafb;
            font-weight: 600;
            color: #4b5563;
            text-transform: uppercase;
            font-size: 12px;
            letter-spacing: 0.05em;
        }
        
        tr:nth-child(even) {
            background-color: #fcfcfc;
        }
        
        .status {
            padding: 4px 8px;
            border-radius: 9999px;
            font-size: 12px;
            font-weight: 500;
            text-transform: capitalize;
        }
        
        .status.completed, .status.shipped { background: #dcfce7; color: #166534; }
        .status.pending { background: #fef08a; color: #854d0e; }
        .status.cancelled { background: #fee2e2; color: #991b1b; }
        
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            font-size: 12px;
            color: #9ca3af;
        }
        
        @media print {
            body { padding: 0; }
            @page { margin: 2cm; }
        }
    </style>
</head>
<body>

    <div class="header">
        <div class="brand">
            <div class="logo">O</div>
            <div class="title">
                <h1>Executive Business Report</h1>
                <p>Ogani E-Commerce Management Portal</p>
            </div>
        </div>
        <div class="meta">
            <p><strong>Date:</strong> <?= date('F d, Y - H:i') ?></p>
            <p><strong>Period:</strong> <?= isset($period) && is_numeric($period) ? $period . ' Days' : 'All Time' ?></p>
            <p><strong>Generated By:</strong> <?= esc(session()->get('fullName') ?? 'Administrator') ?></p>
        </div>
    </div>

    <div class="kpi-container">
        <div class="kpi-card">
            <div class="kpi-label">Total Revenue</div>
            <p class="kpi-value">Rp <?= number_format($stats['revenueToday'] ?? 0, 0, ',', '.') ?></p>
        </div>
        <div class="kpi-card">
            <div class="kpi-label">Total Orders</div>
            <p class="kpi-value"><?= number_format($stats['totalOrders'] ?? 0, 0, ',', '.') ?></p>
        </div>
        <div class="kpi-card">
            <div class="kpi-label">Pending Orders</div>
            <p class="kpi-value"><?= number_format($stats['pendingOrders'] ?? 0, 0, ',', '.') ?></p>
        </div>
        <div class="kpi-card">
            <div class="kpi-label">Avg. Order Value</div>
            <p class="kpi-value">Rp <?= number_format($stats['averageOrderValue'] ?? 0, 0, ',', '.') ?></p>
        </div>
    </div>

    <h2 class="section-title">Sales Overview</h2>
    <div style="height: 300px; width: 100%; margin-bottom: 40px; border: 1px solid #e5e7eb; padding: 20px; box-sizing: border-box; border-radius: 8px;">
        <canvas id="salesChart"></canvas>
    </div>

    <h2 class="section-title">Transaction History</h2>
    <table>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Invoice</th>
                <th>Customer Name</th>
                <th>Date</th>
                <th style="text-align: right;">Total Price</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <?php if (isset($stats['recentOrders']) && !empty($stats['recentOrders'])): ?>
                <?php foreach ($stats['recentOrders'] as $order): ?>
                <tr>
                    <td><?= esc($order['orderId']) ?></td>
                    <td><?= esc($order['invoiceCode'] ?? '#ORD-'.$order['orderId']) ?></td>
                    <td><?= esc($order['user']['fullName'] ?? 'Unknown User') ?></td>
                    <td><?= date('M d, Y', strtotime($order['orderTime'])) ?></td>
                    <td style="text-align: right; font-weight: 500;">Rp <?= number_format($order['totalPrice'] ?? 0, 0, ',', '.') ?></td>
                    <td>
                        <span class="status <?= strtolower($order['orderStatus'] ?? 'pending') ?>">
                            <?= esc($order['orderStatus'] ?? 'pending') ?>
                        </span>
                    </td>
                </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr><td colspan="6" style="text-align: center; color: #6b7280;">No transactions found for this period.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="footer">
        <p>&copy; <?= date('Y') ?> Ogani E-Commerce. CONFIDENTIAL - For Internal Use Only.</p>
    </div>

    <?php
    $chartLabels = isset($stats['chartData']['labels']) ? json_encode($stats['chartData']['labels']) : '[]';
    $chartData = isset($stats['chartData']['data']) ? json_encode($stats['chartData']['data']) : '[]';
    ?>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
    document.addEventListener("DOMContentLoaded", function() {
        const ctx = document.getElementById('salesChart');
        if (ctx) {
            new Chart(ctx, {
                type: 'line',
                data: {
                    labels: <?= $chartLabels ?>,
                    datasets: [{
                        label: 'Revenue',
                        data: <?= $chartData ?>,
                        borderColor: '#2B5C38',
                        backgroundColor: 'rgba(43, 92, 56, 0.1)',
                        tension: 0.4,
                        fill: true,
                        pointBackgroundColor: '#4BAE4F'
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    animation: {
                        onComplete: function() {
                            // Automatically trigger print dialog after chart finishes rendering
                            setTimeout(function() {
                                window.print();
                            }, 500);
                        }
                    },
                    scales: {
                        y: { beginAtZero: true }
                    }
                }
            });
        } else {
            window.print();
        }
    });
    </script>
</body>
</html>
